//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionApiFramework.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using ElectionApiFramework.Models;
    using System.Collections.Generic;

    public partial class ElectionEntities : DbContext
    {
        public ElectionEntities()
            : base("name=ElectionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tlkpConstituancy> tlkpConstituancies { get; set; }
        public virtual DbSet<tlkpParish> tlkpParishes { get; set; }
        public virtual DbSet<tlkpParty> tlkpParties { get; set; }
        public virtual DbSet<tlkpVillage> tlkpVillages { get; set; }
        public virtual DbSet<tblElection> tblElections { get; set; }
        public virtual DbSet<tblAddress> tblAddresses { get; set; }
        public virtual DbSet<tblCandidate> tblCandidates { get; set; }
        public virtual DbSet<tblPerson> tblPersons { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }

        public virtual IEnumerable<ElectionResult> ElectionTally()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteStoreQuery<ElectionResult>("ElectionTally");
        }

        public virtual IEnumerable<PartyByVillages> PartyByVillages()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteStoreQuery<PartyByVillages>("PartyByVillages");
        }

        public virtual IEnumerable<ElectionSummary> ElectionSummary()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteStoreQuery<ElectionSummary>("ElectionSummary");
        }

        public virtual int CloseElection()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CloseElection");
        }
    
        public virtual int StartElection()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("StartElection");
        }
    }
}
