//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionApiFramework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAddress
    {
        public int AddressID { get; set; }
        public string Street { get; set; }
        public int Village { get; set; }
        public int Parish { get; set; }
        public string Postcode { get; set; }
        public int Constituancy { get; set; }
        public bool IsCurrent { get; set; }
        public int PersonID { get; set; }
        public Nullable<System.DateTime> DateMoved { get; set; }
    }
}
