//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionApiFramework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblElection
    {
        public int ID { get; set; }
        public int VotersID { get; set; }
        public System.DateTime ElectionDate { get; set; }
        public int Constituancy { get; set; }
        public int Candidate1 { get; set; }
        public int Candidate2 { get; set; }
        public int Candidate3 { get; set; }
        public int Candidate4 { get; set; }
        public int Candidate5 { get; set; }
        public int Candidate6 { get; set; }
        public int Candidate7 { get; set; }
        public int Candidate8 { get; set; }
        public int Candidate9 { get; set; }
    }
}
