//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionApiFramework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPerson
    {
        public int PersonID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public System.DateTime DOB { get; set; }
        public string Alias { get; set; }
        public Nullable<int> Address { get; set; }
        public System.DateTime RegDate { get; set; }
        public bool vFlag { get; set; }
        public string Pin { get; set; }
        public Nullable<int> SocialSecurity { get; set; }
        public string PersonImage { get; set; }
        public string QrCode { get; set; }
    }
}
